import type { Metadata } from "next";
import { Lora } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";

const font = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LLM Interactive Fiction Wrapper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
